config/routes.rb
Rails.application.routes.draw do

  root 'client#index'

  get 'show_eats/:id' => 'client#show_eats', as: 'show_eats'
  get 'show_foods/:id' => 'client#show_foods', as: 'show_foods'

  namespace :admin do
    root 'foods#index'
    resources :eats
    resources :foods
  end

  devise_for :users

end

app/models/eat.rb
class Eat < ActiveRecord::Base
  has_many :foods
end

app/models/food.rb
class Food < ActiveRecord::Base
  belongs_to :eat
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  has_many :foods


  devise :database_authenticatable, :registerable,
         :rememberable, :trackable

  validates :name, presence: true
  validates :email, presence: true
  validates :password, presence: true
end

app/controllers/admin/eats_controller.rb
class Admin::EatsController < AdminController

  def index
    @eats = Eat.all
  end

  def show
    @eat = Eat.find(params[:id])
    @foods = @eat.foods.order(created_at: :desc)
  end

  def new
  end

  def edit
  end
end

app/controllers/admin/foods_controller.rb
class Admin::FoodsController < AdminController

  def index
    @foods = Food.all.order(created_at: :desc)
  end

  def show
    @food = Food.find(params[:id])
  end

  def new
    @food = Food.new
  end

  def create
    par = food_params
    par[:user_id] = current_user.id
    @food = Food.new(par)

    if @food.save
      flash[:success] = "Your food has been created successfully"
      redirect_to root_url
      else
      render 'new'
    end
  end

  def edit
    @food = Food.find(params[:id])
  end

  def destroy
  end

  def update
  end

private
  def food_params
    params.require(:food).permit(:id, :name, :price, :description, :eat_id)
  end

  def correct_user
    @food = Food.find(params[:id])
    if @food.user != current_user
      flash[:danger] = 'This is not your food.'
      redirect_to root_url
    end
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  layout 'admin'

  before_action :auth

  private

  def auth
    user = current_user

    if user.admin?
      authenticate_user!
      return true
    end

    redirect_to root_path
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/client_controller.rb
class ClientController < ApplicationController

  def index
    @eats = Eat.all
    @foods = Food.all
  end

  def show_eats
    @eat = Eat.find(params[:id])
    @foods = @eat.foods.order(created_at: :desc)
  end

  def show_foods
    @food = Food.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/client_helper.rb
module ClientHelper
end

app/helpers/eats_helper.rb
module EatsHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/admin/eats/edit.html.erb
<h1>Eats#edit</h1>
<p>Find me in app/views/eats/edit.html.erb</p>

app/views/admin/eats/index.html.erb
<h1><%= @eat.name %></h1>
<%= render 'shared/foods' %>

app/views/admin/eats/new.html.erb
<h1>Eats#new</h1>
<p>Find me in app/views/eats/new.html.erb</p>

app/views/admin/eats/show.html.erb
<h1><%= @eat.name %></h1>

<%= render 'shared/foods' %>

app/views/admin/foods/edit.html.erb
<h1>Foods#edit</h1>
<p>Find me in app/views/foods/edit.html.erb</p>

app/views/admin/foods/index.html.erb
<h1>All Foods and Restaurants</h1>

<%= render 'shared/foods' %>

app/views/admin/foods/new.html.erb
<h1>Create Foods</h1>

<%= form_for [:admin, @food] do |f|%>

    <div class="form-group">
      <%= f.label :eat %><br />
      <%= f.collection_select :eat_id, Eat.all, :id, :name, {}, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :name %><br />
      <%= f.text_field :name, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :price %><br />
      <%= f.text_field :price, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :description %><br />
      <%= f.text_area :description, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.submit class: 'btn btn-primary' %><br />
    </div>

<% end %>

app/views/admin/foods/show.html.erb
<%= link_to 'List of all foods', admin_root_path %> <%= @food.name %>

<h1><%= @food.name %></h1>
<p>
  Eat: <%= link_to @food.eat.name, admin_eat_path(@food.eat)%>, by: <%= @food.user.name %>
</p>

<p>
  <b>Details:</b><br />
  Description: <%= @food.description %>
</p>
<p>
  Price: <%= @food.price %>
</p>

<p>
  <% if current_user == @food.user %>
  <%= link_to 'Edit food', admin_edit_food_path, class: 'btn btn-primary' %>
  <%= link_to 'Delete food', admin_food_path(@food), method: :delete, class: 'btn btn-danger' %>
  <% end%>
</p>

app/views/client/index.html.erb
<h1>Welcome!</h1>

<div class="row">
  <div class="col-sm-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Eats. Restaurants and cafe </h3>
      </div>
      <div class="panel-body">
        <ul>
          <li><%= link_to 'All', root_url %></li>
          <% Eat.all.each do |eat|  %>
              <li><%= link_to eat.name, show_eats_path(eat) %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>

  <div class="col-sm-8">

    <% @foods.each do |food|%>
        <div class="panel panel-default">
          <div class="panel-body">
            <p>Eat: <%= link_to food.eat.name, show_eats_path(food.eat.id)%></p>
            <p>Food: <%= link_to food.name, show_foods_path(food) %></p>
          </div>
        </div>
    <% end %>

  </div>
</div>

app/views/client/show_eats.html.erb
<h1><%= @eat.name %></h1>

<div class="row">
  <div class="col-sm-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Eats. Restaurants and cafe </h3>
      </div>
      <div class="panel-body">
        <ul>
          <li><%= link_to 'All', root_url %></li>
          <% Eat.all.each do |eat|  %>
              <li><%= link_to eat.name, show_eats_path(eat) %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>

  <div class="col-sm-8">

    <% @foods.each do |food|%>
        <div class="panel panel-default">
          <div class="panel-body">
            <!--<p>Eat: <%= link_to food.eat.name, show_eats_path(food.eat) %></p>-->
            <h4>Food: <%= link_to food.name, show_foods_path(food) %></h4>
          </div>
        </div>
    <% end %>

  </div>
</div>

app/views/client/show_foods.html.erb
<%= link_to 'List of all foods', root_path %> <%= @food.name %>

<h1><%= @food.name %></h1>
<p>
  Eat: <%= link_to @food.eat.name, show_eats_path(@food.eat)%>, by: <%= @food.user.name %>
</p>

<p>
  <b>Details:</b><br />
  Description: <%= @food.description %>
</p>
<p>
  Price: <%= @food.price %>
</p>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-static-top navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <%= link_to 'Eat Food', root_path, class: "navbar-brand"%>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <div class="nav navbar-nav navbar-right">
        <% if user_signed_in?  %>
            <li class="navbar-text">Hello, <%= current_user.name %></li>
            <li><%= link_to 'Create food', new_admin_food_path %></li>
            <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
            <% else %>
                <%= link_to 'Sign up', new_user_registration_path, class: 'btn btn-default navbar-btn' %>
                <%= link_to 'Log in', new_user_session_path, class: 'btn btn-default navbar-btn' %>
            <% end %>
      </div>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tamak Admin</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/navbar' %>

<div class="container">
  <% flash.each do |type, message| %>
      <div class="alert alert-<%= type %>" role="alert"><%= message %></div>
  <% end %>

  <%= yield %>
</div>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tamak</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/navbar' %>

<div class="container">
  <% flash.each do |type, message| %>
      <div class="alert alert-<%= type %>" role="alert"><%= message %></div>
  <% end %>

  <%= yield %>
</div>

</body>
</html>

app/views/shared/_foods.html.erb
<div class="row">
  <div class="col-sm-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Eats. Restaurants and cafe </h3>
      </div>
      <div class="panel-body">
        <ul>
         <li><%= link_to 'All', admin_root_url %></li>
          <% Eat.all.each do |eat|  %>
              <li><%= link_to eat.name, admin_eat_path(eat) %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>

  <div class="col-sm-8">

    <% @foods.each do |food|%>
        <div class="panel panel-default">
          <div class="panel-body">
            <p>Eat: <%= link_to food.eat.name, admin_eat_path(food.eat) %></p>
            <h4>Food: <%= link_to food.name, admin_food_path(food) %></h4>
            <p>User: <%= link_to food.user.name, '#' %></p>
          </div>
        </div>
    <% end %>

  </div>
</div>